// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: disaster.proto

package disaster

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportDisasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageURLs     []string               `protobuf:"bytes,4,rep,name=imageURLs,proto3" json:"imageURLs,omitempty"`
	ContributorID string                 `protobuf:"bytes,5,opt,name=contributorID,proto3" json:"contributorID,omitempty"`
	Location      *Coordinates           `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDisasterRequest) Reset() {
	*x = ReportDisasterRequest{}
	mi := &file_disaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDisasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDisasterRequest) ProtoMessage() {}

func (x *ReportDisasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDisasterRequest.ProtoReflect.Descriptor instead.
func (*ReportDisasterRequest) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{0}
}

func (x *ReportDisasterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReportDisasterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ReportDisasterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ReportDisasterRequest) GetImageURLs() []string {
	if x != nil {
		return x.ImageURLs
	}
	return nil
}

func (x *ReportDisasterRequest) GetContributorID() string {
	if x != nil {
		return x.ContributorID
	}
	return ""
}

func (x *ReportDisasterRequest) GetLocation() *Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

type Coordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinates) Reset() {
	*x = Coordinates{}
	mi := &file_disaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinates) ProtoMessage() {}

func (x *Coordinates) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinates.ProtoReflect.Descriptor instead.
func (*Coordinates) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Coordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ReportDisasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportDisasterResponse) Reset() {
	*x = ReportDisasterResponse{}
	mi := &file_disaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDisasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDisasterResponse) ProtoMessage() {}

func (x *ReportDisasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDisasterResponse.ProtoReflect.Descriptor instead.
func (*ReportDisasterResponse) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{2}
}

func (x *ReportDisasterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportDisasterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDisasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisasterRequest) Reset() {
	*x = GetDisasterRequest{}
	mi := &file_disaster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisasterRequest) ProtoMessage() {}

func (x *GetDisasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisasterRequest.ProtoReflect.Descriptor instead.
func (*GetDisasterRequest) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{3}
}

func (x *GetDisasterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDisasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageURLs     []string               `protobuf:"bytes,5,rep,name=imageURLs,proto3" json:"imageURLs,omitempty"`
	ContributorID string                 `protobuf:"bytes,6,opt,name=contributorID,proto3" json:"contributorID,omitempty"`
	Location      *Coordinates           `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Resources     []*Resource            `protobuf:"bytes,11,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDisasterResponse) Reset() {
	*x = GetDisasterResponse{}
	mi := &file_disaster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDisasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDisasterResponse) ProtoMessage() {}

func (x *GetDisasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDisasterResponse.ProtoReflect.Descriptor instead.
func (*GetDisasterResponse) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{4}
}

func (x *GetDisasterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDisasterResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetDisasterResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetDisasterResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetDisasterResponse) GetImageURLs() []string {
	if x != nil {
		return x.ImageURLs
	}
	return nil
}

func (x *GetDisasterResponse) GetContributorID() string {
	if x != nil {
		return x.ContributorID
	}
	return ""
}

func (x *GetDisasterResponse) GetLocation() *Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GetDisasterResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDisasterResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetDisasterResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDisasterResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Location      *Coordinates           `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_disaster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_disaster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_disaster_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetLocation() *Coordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_disaster_proto protoreflect.FileDescriptor

const file_disaster_proto_rawDesc = "" +
	"\n" +
	"\x0edisaster.proto\x12\bdisaster\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n" +
	"\x15ReportDisasterRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1c\n" +
	"\timageURLs\x18\x04 \x03(\tR\timageURLs\x12$\n" +
	"\rcontributorID\x18\x05 \x01(\tR\rcontributorID\x121\n" +
	"\blocation\x18\x06 \x01(\v2\x15.disaster.CoordinatesR\blocation\"G\n" +
	"\vCoordinates\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"@\n" +
	"\x16ReportDisasterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"$\n" +
	"\x12GetDisasterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa6\x03\n" +
	"\x13GetDisasterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x1c\n" +
	"\timageURLs\x18\x05 \x03(\tR\timageURLs\x12$\n" +
	"\rcontributorID\x18\x06 \x01(\tR\rcontributorID\x121\n" +
	"\blocation\x18\a \x01(\v2\x15.disaster.CoordinatesR\blocation\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x120\n" +
	"\tresources\x18\v \x03(\v2\x12.disaster.ResourceR\tresources\"u\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x121\n" +
	"\blocation\x18\x04 \x01(\v2\x15.disaster.CoordinatesR\blocation2\xb2\x01\n" +
	"\x0fDisasterService\x12S\n" +
	"\x0eReportDisaster\x12\x1f.disaster.ReportDisasterRequest\x1a .disaster.ReportDisasterResponse\x12J\n" +
	"\vGetDisaster\x12\x1c.disaster.GetDisasterRequest\x1a\x1d.disaster.GetDisasterResponseB Z\x1eshared/proto/disaster;disasterb\x06proto3"

var (
	file_disaster_proto_rawDescOnce sync.Once
	file_disaster_proto_rawDescData []byte
)

func file_disaster_proto_rawDescGZIP() []byte {
	file_disaster_proto_rawDescOnce.Do(func() {
		file_disaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disaster_proto_rawDesc), len(file_disaster_proto_rawDesc)))
	})
	return file_disaster_proto_rawDescData
}

var file_disaster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_disaster_proto_goTypes = []any{
	(*ReportDisasterRequest)(nil),  // 0: disaster.ReportDisasterRequest
	(*Coordinates)(nil),            // 1: disaster.Coordinates
	(*ReportDisasterResponse)(nil), // 2: disaster.ReportDisasterResponse
	(*GetDisasterRequest)(nil),     // 3: disaster.GetDisasterRequest
	(*GetDisasterResponse)(nil),    // 4: disaster.GetDisasterResponse
	(*Resource)(nil),               // 5: disaster.Resource
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_disaster_proto_depIdxs = []int32{
	1, // 0: disaster.ReportDisasterRequest.location:type_name -> disaster.Coordinates
	1, // 1: disaster.GetDisasterResponse.location:type_name -> disaster.Coordinates
	6, // 2: disaster.GetDisasterResponse.createdAt:type_name -> google.protobuf.Timestamp
	6, // 3: disaster.GetDisasterResponse.updatedAt:type_name -> google.protobuf.Timestamp
	5, // 4: disaster.GetDisasterResponse.resources:type_name -> disaster.Resource
	1, // 5: disaster.Resource.location:type_name -> disaster.Coordinates
	0, // 6: disaster.DisasterService.ReportDisaster:input_type -> disaster.ReportDisasterRequest
	3, // 7: disaster.DisasterService.GetDisaster:input_type -> disaster.GetDisasterRequest
	2, // 8: disaster.DisasterService.ReportDisaster:output_type -> disaster.ReportDisasterResponse
	4, // 9: disaster.DisasterService.GetDisaster:output_type -> disaster.GetDisasterResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_disaster_proto_init() }
func file_disaster_proto_init() {
	if File_disaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disaster_proto_rawDesc), len(file_disaster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_disaster_proto_goTypes,
		DependencyIndexes: file_disaster_proto_depIdxs,
		MessageInfos:      file_disaster_proto_msgTypes,
	}.Build()
	File_disaster_proto = out.File
	file_disaster_proto_goTypes = nil
	file_disaster_proto_depIdxs = nil
}
