apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: relief-ops
data:
  USER_GRPC_ADDR: :9001
  HTTP_ADDR: :8080
  DISASTER_GRPC_ADDR: :9002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: relief-ops
data:
  POSTGRES_USER: admin
  POSTGRES_DB: reliefops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: relief-ops
data:
  KAFKA_BROKERS: apache-kafka:9092