apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db
  namespace: relief-ops
  labels:
    app: redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command:
            - /bin/bash
            - -c
            - |
              # Export the Redis password from the environment variable
              export REDIS_PASSWORD=$REDIS_PASSWORD

              # Create necessary directories and files
              mkdir -p /run
              mkdir -p /data
              mkdir -p /etc/redis
              mkdir -p /var/log/redis
              touch /run/redis.pid
              touch /var/log/redis/redis.log

              # Create Redis configuration file
              cat > /etc/redis/redis.conf <<EOF

              # Networking
              bind 0.0.0.0
              port 6379
              protected-mode no
              timeout 300

              # General
              pidfile /run/redis.pid
              loglevel notice
              logfile "/var/log/redis/redis.log"
              databases 16
              always-show-logo no
              hide-user-data-from-log yes

              # Snapshotting
              save 3600 1 300 100 60 10000
              dbfilename dump.rdb
              dir /data

              # Memory management
              maxmemory 256mb
              maxmemory-policy volatile-lru

              # Lazy freeing
              lazyfree-lazy-expire yes
              lazyfree-lazy-user-del no
              lazyfree-lazy-user-flush no
              EOF

              # Start Redis server with the specified configuration
              redis-server /etc/redis/redis.conf
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db
  namespace: relief-ops
  labels:
    app: redis-db
spec:
  type: ClusterIP
  selector:
    app: redis-db
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: relief-ops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi